In [31]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.13.0-rc0


In [32]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [33]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [34]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.0416633 , -0.639413  , -0.02037774,  0.23814324, -0.5286192 ,
        -0.45933598, -0.00926862,  0.49297255, -0.49076128,  0.6349144 ]],
      dtype=float32)

In [35]:
tf.nn.softmax(predictions).numpy()

array([[0.10254233, 0.0518938 , 0.09637382, 0.12480539, 0.05797391,
        0.06213294, 0.09745042, 0.16102907, 0.06021076, 0.18558756]],
      dtype=float32)

In [36]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [37]:
loss_fn(y_train[:1], predictions).numpy()

2.778479

In [38]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [39]:
model.fit(x_train, y_train, epochs=200)

Epoch 1/200
1875/1875 [==============================] - 2s 756us/step - loss: 0.3003 - accuracy: 0.9128
Epoch 2/200
1875/1875 [==============================] - 1s 707us/step - loss: 0.1435 - accuracy: 0.9571
Epoch 3/200
1875/1875 [==============================] - 1s 696us/step - loss: 0.1039 - accuracy: 0.9683
Epoch 4/200
1875/1875 [==============================] - 1s 713us/step - loss: 0.0859 - accuracy: 0.9729
Epoch 5/200
1875/1875 [==============================] - 1s 719us/step - loss: 0.0732 - accuracy: 0.9777
Epoch 6/200
1875/1875 [==============================] - 1s 690us/step - loss: 0.0655 - accuracy: 0.9786
Epoch 7/200
1875/1875 [==============================] - 1s 706us/step - loss: 0.0577 - accuracy: 0.9814
Epoch 8/200
1875/1875 [==============================] - 1s 712us/step - loss: 0.0534 - accuracy: 0.9829
Epoch 9/200
1875/1875 [==============================] - 1s 699us/step - loss: 0.0481 - accuracy: 0.9841
Epoch 10/200
1875/1875 [==============================]

In [40]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.2174 - accuracy: 0.9792 - 167ms/epoch - 533us/step


[0.21735326945781708, 0.979200005531311]

In [41]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [42]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.48569089e-27, 5.31821762e-31, 3.88437688e-18, 2.72125900e-23,
        5.70355201e-37, 1.36453816e-26, 0.00000000e+00, 1.00000000e+00,
        5.24386557e-37, 5.89770988e-20],
       [9.43191510e-29, 7.77720082e-16, 1.00000000e+00, 6.81264222e-25,
        0.00000000e+00, 1.54498406e-21, 1.45682079e-27, 0.00000000e+00,
        6.09797145e-31, 0.00000000e+00],
       [4.88681251e-30, 1.00000000e+00, 5.79823681e-21, 1.12851714e-27,
        1.01181238e-12, 1.90248520e-24, 1.72354244e-27, 1.43566365e-12,
        9.78999664e-14, 1.14011856e-26],
       [1.00000000e+00, 4.08488754e-32, 4.58292470e-18, 1.63049892e-26,
        3.57116359e-31, 3.24367992e-22, 3.59308638e-21, 2.64691221e-20,
        1.41034895e-31, 3.41023953e-25],
       [6.02574792e-26, 0.00000000e+00, 1.21215451e-20, 4.41082682e-30,
        1.00000000e+00, 8.28847448e-27, 4.18879767e-25, 5.94593412e-14,
        1.37086460e-29, 5.80314852e-10]], dtype=float32)>